# Codemagic Build Configuration

# Flutter workflow example - modify for Capacitor
workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_VERSION: 16.1
      xcode: 16.1
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set up Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     archive \
                     -allowProvisioningUpdates
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportPath $CM_BUILD_DIR/build \
                     -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/*.ipa
      - $CM_BUILD_DIR/**/*.xcarchive
